import "./globals.css"; 
import { ralewayFont } from '@/utils/fonts';

export const metadata = {
  title: "Ringgaard Motorsport",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={ralewayFont.className}>
        {children}
      </body>
    </html>
  );
}
